name: Git Checks

on: [push]

jobs:
    block-merge-synchronized:
        runs-on: ubuntu-18.04

        steps:
            - uses: actions/checkout@v2
            - run: |
                  git fetch --prune --unshallow
            - uses: involic/synchronized-target-branch-action@master
              with:
                  branch: 'master'